on:
  pull_request:
    branches: [master]
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    name: .NET on ${{ matrix.runs-on }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [windows-latest]
        configuration: [Release, Debug]
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        id: setup-dotnet
        uses: actions/setup-dotnet@v3
        with:
          cache: true
          dotnet-version: 7.x
          cache-dependency-path: "**/packages.lock.json"

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Build
        id: build
        run: dotnet build --no-restore -c ${{ matrix.configuration }} ${{ github.workspace }}\SIT.Launcher\SIT.Launcher.csproj

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Rage-SIT-Build-${{ matrix.configuration }}
          path: ${{ github.workspace }}\SIT.Launcher\bin\${{ matrix.configuration }}\win-x64\publish
          if-no-files-found: error
