on:
  push:
    tags:
      - v*

jobs:
  publish:
    if: contains(github.ref, 'master')
    name: .NET on ${{ matrix.runs-on }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ windows-latest ]
        configuration: [ Release ]
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Build
        id: build
        run: dotnet publish --no-restore -c Release .\SIT.Launcher\SIT.Launcher.csproj
      
      - name: Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: ${{ github.workspace }}\SIT.Launcher\bin\${{ matrix.configuration }}\publish
